### ISSUE TITLE
Shall we require a minimum cmake version?

### ISSUE THREAD

**Issue by KubaO** [sauter-hq/cmake-ide-support#2]
The commands used in this script require at least cmake 2.8.11 due to `EXCLUDE_FROM_DEFAULT_BUILD` target property.

Shouln't a `cmake_minimum_required(VERSION 2.8.11)` be within the function, protected by a `  cmake_policy(PUSH)` and `  cmake_policy(POP)` within the function?

**Comment by daminetreg** [comment]
Thanks for the feedback.

Yes this check would be welcome, I would be happy to review and merge a PR about it.

Thanks.

**Comment by daminetreg** [comment]
Closing as no more activity for a month.
